name: Publish NuGet Package

on:
  push:
    branches:
      - main  # For beta releases
  release:
    types: [published]  # For full releases

jobs:
  build-and-publish:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    - name: Restore
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release --no-restore

    - name: Determine version
      id: version
      run: |
        if [ "${{ github.event_name }}" == "release" ]; then
          echo "version=${{ github.event.release.tag_name }}" >> $GITHUB_OUTPUT
        else
          short_sha=$(git rev-parse --short HEAD)
          echo "version=1.0.0-beta-${short_sha}" >> $GITHUB_OUTPUT
        fi

    - name: Pack
      run: dotnet pack ./src/Krp/Krp.csproj `
        --configuration Release `
        -p:PackageVersion=${{ steps.version.outputs.version }} `
        --no-build `
        --output ./nupkgs

    - name: Push
      run: dotnet nuget push ./nupkgs/*.nupkg `
        --source https://api.nuget.org/v3/index.json `
        --api-key ${{ secrets.NUGET_API_KEY }} `
        --skip-duplicate
