name: Publish NuGet Package

on:
  push:
    branches:
      - main  # For beta releases
  release:
    types: [published]  # For full releases

jobs:
  build-and-publish:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    - name: Restore
      run: dotnet restore --locked-mode

    - name: Build
      run: dotnet build --configuration Release --no-restore

    - name: Determine version
      id: version
      run: |
        if [ "${{ github.event_name }}" == "release" ]; then
          echo "version=${{ github.event.release.tag_name }}" >> $GITHUB_OUTPUT
        else
          short_sha=$(git rev-parse --short HEAD)
          latest_release=$(git tag -l --sort=-creatordate | head -n 1)
          if [ -z "$latest_release" ]; then
            latest_release="1.0.0"
          fi
          echo "version=${latest_release}-beta${{ github.run_number }}-${short_sha}" >> $GITHUB_OUTPUT
        fi

    - name: Pack
      run: dotnet pack --configuration Release --no-build --output ./nupkgs -p:PackageVersion=${{ steps.version.outputs.version }}

    - name: Push
      run: dotnet nuget push ./nupkgs/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate