on:
  workflow_call:

jobs:
  publish-nuget:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: nuget

      - name: dotnet nuget push
        run: |
          dotnet nuget push "*.nupkg" \
            --api-key ${{ secrets.NUGET_API_KEY }} \
            --source https://api.nuget.org/v3/index.json \
            --skip-duplicate
